// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_calc_exceedance_prob
NumericVector cpp_calc_exceedance_prob(NumericVector flow, bool rm_zero, double alpha);
RcppExport SEXP _preMetabolizer_cpp_calc_exceedance_prob(SEXP flowSEXP, SEXP rm_zeroSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type flow(flowSEXP);
    Rcpp::traits::input_parameter< bool >::type rm_zero(rm_zeroSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_calc_exceedance_prob(flow, rm_zero, alpha));
    return rcpp_result_gen;
END_RCPP
}
// flag_z
SEXP flag_z(NumericVector x, int width, double threshold, bool return_z);
RcppExport SEXP _preMetabolizer_flag_z(SEXP xSEXP, SEXP widthSEXP, SEXP thresholdSEXP, SEXP return_zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type return_z(return_zSEXP);
    rcpp_result_gen = Rcpp::wrap(flag_z(x, width, threshold, return_z));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_preMetabolizer_cpp_calc_exceedance_prob", (DL_FUNC) &_preMetabolizer_cpp_calc_exceedance_prob, 3},
    {"_preMetabolizer_flag_z", (DL_FUNC) &_preMetabolizer_flag_z, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_preMetabolizer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
