# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

flag_z <- function(x, width = 5L, threshold = 3.0, return_z = FALSE) {
    .Call(`_preMetabolizer_flag_z`, x, width, threshold, return_z)
}

