# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_calc_exceedance_prob <- function(flow, rm_zero = FALSE) {
    .Call(`_preMetabolizer_cpp_calc_exceedance_prob`, flow, rm_zero)
}

flag_z <- function(x, width = 5L, threshold = 3.0, return_z = FALSE) {
    .Call(`_preMetabolizer_flag_z`, x, width, threshold, return_z)
}

